### ISSUE TITLE
Issues with themeContracts handling null values

### ISSUE THREAD

**Issue by hemlok** [seek-oss/vanilla-extract#44]
Hello 👋 

Very excited about vanilla-extract and wanted to give it a try in Framer with esbuild.

Unfortunately, I'm having some difficulties with the output. I wonder if this could be a bug with the esbuild plugin, or perhaps a mistake on my end!!

Here are my files:
```typescript
// definitions.ts
import { createThemeVars } from "@vanilla-extract/css"

export const theme = createThemeVars({
    color: {
        tint: null,
        tintDark: null,
    },
})
```

```typescript
// dark.css.ts
import { createTheme } from "@vanilla-extract/css"
import { theme } from "./definitions"

export const dark = createTheme(
    theme,
    {
        color: {
            tint: "#0099ff",
            tintDark: "#0088ff",
        },
    },
    "dark-theme"
)
```

Elsewhere, I import `dark` and consume it in react:
```typescript
import { dark } from "./dark.css"
// ...

<div className={dark}>
```

My output from esbuild is then: 
```css
/* vanilla-extract-css-ns:vekter/../fresco/src/tokens/colors/theme/dark.css.ts.vanilla.css?source=LmRhcmtfZGFyay10aGVtZV9fMWt1cWlxMTAgewogIG51bGw6ICMwMDg4ZmY7Cn0= */
.dark_dark-theme__1kuqiq10 {
  null: #0088ff;
}
```

Dependencies:
```json
"@vanilla-extract/css": "^0.3.0",
"@vanilla-extract/esbuild-plugin": "^0.1.2",
```

**Comment by hemlok** [comment]
Interestingly I get similar issues when trying to use the `style` api with theme colors 🤔 

```typescript
// Badge.css.ts

import { theme } from "./definitions"
import { style } from "@vanilla-extract/css"

export const badge = style({
    display: "inlineBlock",
    padding: "3px 5px",
    borderRadius: 4,
    color: theme.color.tint,
    fontSize: 10,
    lineHeight: 1.1,
    textAlign: "center",
    textTransform: "uppercase",
    selectors: {
        "&.primary": {
            background: theme.color.tint,
        },
    },
})

```

```css
/* vanilla-extract-css-ns:vekter/../fresco/src/components/Badge.css.ts.vanilla.css?source=Ll8xNTg0d29lMCB7CiAgZGlzcGxheTogaW5saW5lQmxvY2s7CiAgcGFkZGluZzogM3B4IDVweDsKICBib3JkZXItcmFkaXVzOiA0cHg7CiAgY29sb3I6IG51bGw7CiAgZm9udC1zaXplOiAxMHB4OwogIGxpbmUtaGVpZ2h0OiAxLjE7CiAgdGV4dC1hbGlnbjogY2VudGVyOwogIHRleHQtdHJhbnNmb3JtOiB1cHBlcmNhc2U7Cn0KLl8xNTg0d29lMC5wcmltYXJ5IHsKICBiYWNrZ3JvdW5kOiBudWxsOwp9 */
._1584woe0 {
  display: inlineBlock;
  padding: 3px 5px;
  border-radius: 4px;
  color: null;
  font-size: 10px;
  line-height: 1.1;
  text-align: center;
  text-transform: uppercase;
}
._1584woe0.primary {
  background: null;
}
```
