### ISSUE TITLE
Should throw an error when compiling invalid media query syntax

### ISSUE THREAD

**Issue by roginfarrer** [seek-oss/vanilla-extract#708]
### Describe the bug

```tsx
style({
  '@media': {
    '@media screen and (min-width: 640px)': {
      color: 'blue',
    },
  }
});
```

This compiles without an error, and emits the following CSS:

```css
@media @media screen and (min-width: 640px) {
  .hash {
    color: blue;
  }
}
```

This should throw an error during build.

### Link to reproduction

https://codesandbox.io/s/inspiring-herschel-peffi6?file=/src/App.css.ts

### System Info

- ve/css: 1.7.1
- ve/webpack-plugin: 2.1.10
